<?php
$page_title = 'Site-Wide Settings';
require_once 'includes/header.php';

$success_message = '';
$error_message = '';

if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['save_settings'])) {
    // Handle Media Library Selections
    $logo_path = $_POST['logo_path'] ?? get_setting('logo_path', '/VIVA/v.jpeg');
    $favicon_path = $_POST['favicon_path'] ?? get_setting('favicon_path', '');
    $hero_bg_path = $_POST['hero_bg_path'] ?? get_setting('hero_bg_path', '');
    $about_image_path = $_POST['about_image_path'] ?? get_setting('about_image_path', '');
    $services_bg_path = $_POST['services_bg_path'] ?? get_setting('services_bg_path', '');

    // Toggle style settings
    $primary_color = !empty($_POST['primary_color']) ? h($_POST['primary_color']) : '#FF5722';
    $maintenance_mode = isset($_POST['maintenance_mode']) ? '1' : '0';

    // Collect and sanitize data
    $new_settings = [
        'site_name' => h($_POST['site_name'] ?? 'VIVA Engineering'),
        'site_title' => h($_POST['site_title'] ?? ''),
        'contact_email' => h($_POST['contact_email'] ?? ''),
        'enquiry_email' => h($_POST['enquiry_email'] ?? ''),
        'whatsapp_number' => h($_POST['whatsapp_number'] ?? ''),
        'contact_phone' => h($_POST['contact_phone'] ?? ''),
        'address' => h($_POST['address'] ?? ''),
        'working_hours' => h($_POST['working_hours'] ?? ''),
        'facebook_url' => h($_POST['facebook_url'] ?? ''),
        'twitter_url' => h($_POST['twitter_url'] ?? ''),
        'linkedin_url' => h($_POST['linkedin_url'] ?? ''),
        'instagram_url' => h($_POST['instagram_url'] ?? ''),
        'primary_color' => $primary_color,
        'logo_path' => $logo_path,
        'favicon_path' => $favicon_path,
        'meta_description' => h($_POST['meta_description'] ?? ''),
        'meta_keywords' => h($_POST['meta_keywords'] ?? 'slitting machine, rewinding machine'),
        // CTA / Hero controls
        'hero_headline' => h($_POST['hero_headline'] ?? ''),
        'hero_subheadline' => h($_POST['hero_subheadline'] ?? ''),
        'cta_primary_text' => h($_POST['cta_primary_text'] ?? ''),
        'cta_primary_url' => h($_POST['cta_primary_url'] ?? ''),
        'cta_secondary_text' => h($_POST['cta_secondary_text'] ?? ''),
        'cta_secondary_url' => h($_POST['cta_secondary_url'] ?? ''),
        'contact_cta_text' => h($_POST['contact_cta_text'] ?? ''),
        'contact_cta_url' => h($_POST['contact_cta_url'] ?? ''),
        // Map & brochure
        'map_embed' => h($_POST['map_embed'] ?? ''),
        'brochure_url' => h($_POST['brochure_url'] ?? ''),
        // Hero media
        'hero_bg_path' => $hero_bg_path,
        'about_image_path' => $about_image_path,
        'services_bg_path' => $services_bg_path,
        // Analytics & pixels
        'ga_measurement_id' => h($_POST['ga_measurement_id'] ?? ''),
        'meta_pixel_id' => h($_POST['meta_pixel_id'] ?? ''),
        // Ops
        'maintenance_mode' => $maintenance_mode,
        'currency_code' => h($_POST['currency_code'] ?? 'USD'),
    ];

    // Generate the PHP file content
    $content = "<?php\n";
    $content .= "/**\n * VIVA Site-Wide Settings\n * Auto-generated by Admin Panel\n */\n\n";
    $content .= "\$site_settings = [\n";
    foreach ($new_settings as $key => $val) {
        $content .= "    '$key' => '" . addslashes($val) . "',\n";
    }
    $content .= "];\n\n";
    $content .= "/**\n * Helper to get a setting\n */\n";
    $content .= "if (!function_exists('get_setting')) {\n";
    $content .= "    function get_setting(\$key, \$default = '') {\n";
    $content .= "        global \$site_settings;\n";
    $content .= "        return \$site_settings[\$key] ?? \$default;\n";
    $content .= "    }\n";
    $content .= "}\n?>";

    $settings_file = ROOT_PATH . '/data/site-settings.php';
    
    if (file_put_contents($settings_file, $content)) {
        $success_message = 'Settings updated and saved permanently! Your website is now fully synchronized.';
        // Refresh the global variable for the current page load
        $GLOBALS['site_settings'] = $new_settings;
    } else {
        $error_message = 'Error: Failed to save settings. Please check file permissions for data/site-settings.php.';
    }
}
?>

<div class="space-y-8">
    <div class="flex items-center justify-between">
        <div>
            <h1 class="text-2xl font-heading font-bold">Global <span class="text-orange-600">Website Settings</span></h1>
            <p class="text-sm text-gray-400">Manage your company branding, contact details, and SEO defaults.</p>
        </div>
        <button form="settings_form" name="save_settings" type="submit" class="px-6 py-2 bg-orange-600 hover:bg-orange-700 rounded-lg text-sm font-bold transition-all shadow-lg shadow-orange-600/20 active:scale-95">
            <i class="fas fa-save mr-2"></i> Save All Changes
        </button>
    </div>

    <?php if ($success_message): ?>
    <div class="bg-green-500/10 border border-green-500/50 text-green-500 text-sm p-4 rounded-xl flex items-center animate-pulse">
        <i class="fas fa-check-circle mr-3"></i>
        <?php echo $success_message; ?>
    </div>
    <?php endif; ?>

    <form id="settings_form" method="POST" enctype="multipart/form-data" class="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        <!-- General Branding & Info -->
        <div class="space-y-6">
            <div class="card p-6">
                <div class="flex items-center space-x-3 mb-6">
                    <div class="w-8 h-8 bg-orange-600/10 rounded-lg flex items-center justify-center text-orange-600">
                        <i class="fas fa-building text-sm"></i>
                    </div>
                    <h3 class="text-lg font-bold">General Information</h3>
                </div>
                
                <div class="space-y-4">
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Company Name</label>
                        <input type="text" name="site_name" value="<?php echo get_setting('site_name'); ?>" 
                            class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all">
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Website Title (SEO)</label>
                        <input type="text" name="site_title" value="<?php echo get_setting('site_title'); ?>" 
                            class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all">
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Meta Keywords</label>
                        <input type="text" name="meta_keywords" value="<?php echo get_setting('meta_keywords'); ?>" 
                            class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all">
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Primary Brand Color</label>
                        <input type="color" name="primary_color" value="<?php echo get_setting('primary_color', '#FF5722'); ?>" 
                            class="w-20 h-10 bg-black border border-gray-800 rounded-lg cursor-pointer">
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Meta Description</label>
                        <textarea name="meta_description" rows="3"
                            class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all"><?php echo get_setting('meta_description'); ?></textarea>
                    </div>
                </div>
            </div>

            <div class="card p-6">
                <div class="flex items-center space-x-3 mb-6">
                    <div class="w-8 h-8 bg-blue-600/10 rounded-lg flex items-center justify-center text-blue-600">
                        <i class="fas fa-share-alt text-sm"></i>
                    </div>
                    <h3 class="text-lg font-bold">Social Media Links</h3>
                </div>
                
                <div class="space-y-4">
                    <div class="flex items-center space-x-3">
                        <div class="w-10 h-10 bg-gray-900 rounded-lg flex items-center justify-center text-gray-400 border border-gray-800">
                            <i class="fab fa-facebook-f"></i>
                        </div>
                        <input type="text" name="facebook_url" value="<?php echo get_setting('facebook_url'); ?>" placeholder="Facebook URL"
                            class="flex-1 bg-black border border-gray-800 rounded-xl py-2 px-4 text-white focus:outline-none focus:border-orange-600 transition-all">
                    </div>
                    <div class="flex items-center space-x-3">
                        <div class="w-10 h-10 bg-gray-900 rounded-lg flex items-center justify-center text-gray-400 border border-gray-800">
                            <i class="fab fa-linkedin-in"></i>
                        </div>
                        <input type="text" name="linkedin_url" value="<?php echo get_setting('linkedin_url'); ?>" placeholder="LinkedIn URL"
                            class="flex-1 bg-black border border-gray-800 rounded-xl py-2 px-4 text-white focus:outline-none focus:border-orange-600 transition-all">
                    </div>
                    <div class="flex items-center space-x-3">
                        <div class="w-10 h-10 bg-gray-900 rounded-lg flex items-center justify-center text-gray-400 border border-gray-800">
                            <i class="fab fa-instagram"></i>
                        </div>
                        <input type="text" name="instagram_url" value="<?php echo get_setting('instagram_url'); ?>" placeholder="Instagram URL"
                            class="flex-1 bg-black border border-gray-800 rounded-xl py-2 px-4 text-white focus:outline-none focus:border-orange-600 transition-all">
                    </div>
                </div>
            </div>
        </div>

        <!-- Contact & Operations -->
        <div class="space-y-6">
            <div class="card p-6">
                <div class="flex items-center space-x-3 mb-6">
                    <div class="w-8 h-8 bg-green-600/10 rounded-lg flex items-center justify-center text-green-600">
                        <i class="fas fa-headset text-sm"></i>
                    </div>
                    <h3 class="text-lg font-bold">Contact Details</h3>
                </div>
                
                <div class="space-y-4">
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Contact Email</label>
                        <input type="email" name="contact_email" value="<?php echo get_setting('contact_email'); ?>" 
                            class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all">
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Contact Phone</label>
                        <input type="text" name="contact_phone" value="<?php echo get_setting('contact_phone'); ?>" 
                            class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all">
                    </div>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">WhatsApp Number</label>
                            <input type="text" name="whatsapp_number" value="<?php echo get_setting('whatsapp_number'); ?>" 
                                class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all" placeholder="+91 98765 43210">
                        </div>
                        <div>
                            <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Lead / Enquiry Email</label>
                            <input type="email" name="enquiry_email" value="<?php echo get_setting('enquiry_email'); ?>" 
                                class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all" placeholder="sales@yourdomain.com">
                        </div>
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Office Address</label>
                        <textarea name="address" rows="2"
                            class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all"><?php echo get_setting('address'); ?></textarea>
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Business Hours</label>
                        <input type="text" name="working_hours" value="<?php echo get_setting('working_hours'); ?>" 
                            class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all">
                    </div>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Currency Code</label>
                            <input type="text" name="currency_code" value="<?php echo get_setting('currency_code'); ?>" 
                                class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all" placeholder="USD / INR">
                        </div>
                        <div class="flex items-center space-x-3">
                            <input type="checkbox" name="maintenance_mode" value="1" <?php echo get_setting('maintenance_mode') === '1' ? 'checked' : ''; ?> 
                                class="w-5 h-5 text-orange-600 bg-black border-gray-700 rounded focus:ring-orange-600">
                            <label class="text-sm text-gray-300">Enable maintenance mode (show a basic notice to visitors)</label>
                        </div>
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Google Maps Embed (iframe src)</label>
                        <input type="text" name="map_embed" value="<?php echo get_setting('map_embed'); ?>"
                            class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all" placeholder="https://www.google.com/maps/embed?...">
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Brochure / Profile URL (PDF)</label>
                        <input type="text" name="brochure_url" value="<?php echo get_setting('brochure_url'); ?>"
                            class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all" placeholder="/assets/brochure.pdf">
                    </div>
                </div>
            </div>

            <!-- Site Branding Section -->
            <div class="bg-gray-900/50 border border-gray-800 rounded-2xl p-8">
                <div class="flex items-center space-x-4 mb-8">
                    <div class="w-12 h-12 bg-orange-600/20 rounded-xl flex items-center justify-center">
                        <i class="fas fa-palette text-orange-600"></i>
                    </div>
                    <h3 class="text-xl font-heading font-bold text-white">Branding Assets</h3>
                </div>
                
                <div class="flex flex-col items-center justify-center p-8 border-2 border-dashed border-gray-800 rounded-2xl bg-black/40 group hover:border-orange-600/50 transition-all">
                    <div class="relative mb-6">
                        <input type="hidden" name="logo_path" id="logo_path_input" value="<?php echo get_setting('logo_path'); ?>">
                        <div class="w-24 h-24 bg-white rounded-xl flex items-center justify-center shadow-2xl overflow-hidden cursor-pointer" onclick="openSettingsMediaPicker('logo')">
                            <img src="<?php echo resolve_url(get_setting('logo_path')); ?>" id="logo_preview" alt="Current Logo" class="w-20 h-20 object-contain">
                        </div>
                        <div class="absolute -bottom-2 -right-2 w-8 h-8 bg-orange-600 rounded-lg flex items-center justify-center shadow-lg">
                            <i class="fas fa-camera text-white text-xs"></i>
                        </div>
                    </div>
                    <p class="text-gray-500 text-sm mb-6 text-center">Click image to choose from Media Library</p>
                    
                    <button type="button" onclick="openSettingsMediaPicker('logo')" class="bg-gray-800 hover:bg-gray-700 text-white font-bold py-3 px-8 rounded-xl transition-all shadow-lg active:scale-95">
                        Change Logo
                    </button>

                    <div class="mt-8 w-full border-t border-gray-800 pt-6">
                        <div class="flex items-center space-x-3 mb-4">
                            <div class="w-8 h-8 bg-gray-800 rounded-lg flex items-center justify-center text-orange-500">
                                <i class="fas fa-star-half-alt text-sm"></i>
                            </div>
                            <div>
                                <p class="text-sm font-semibold text-white">Favicon</p>
                                <p class="text-xs text-gray-500">Select .ico or .png from library</p>
                            </div>
                        </div>
                        <div class="flex items-center space-x-4">
                            <input type="hidden" name="favicon_path" id="favicon_path_input" value="<?php echo get_setting('favicon_path'); ?>">
                            <div class="w-10 h-10 bg-white rounded-md overflow-hidden flex items-center justify-center cursor-pointer" onclick="openSettingsMediaPicker('favicon')">
                                <img src="<?php echo resolve_url(get_setting('favicon_path')); ?>" id="favicon_preview" alt="Favicon" class="w-8 h-8 object-contain">
                            </div>
                            <button type="button" onclick="openSettingsMediaPicker('favicon')" class="bg-gray-800 hover:bg-gray-700 text-white font-semibold py-2 px-4 rounded-lg transition-all">
                                Change Favicon
                            </button>
                        </div>
                    </div>

                    <div class="mt-8 w-full border-t border-gray-800 pt-6">
                        <div class="flex items-center space-x-3 mb-4">
                            <div class="w-8 h-8 bg-gray-800 rounded-lg flex items-center justify-center text-orange-500">
                                <i class="fas fa-image text-sm"></i>
                            </div>
                            <div>
                                <p class="text-sm font-semibold text-white">Hero Background</p>
                                <p class="text-xs text-gray-500">Select homepage banner image</p>
                            </div>
                        </div>
                        <div class="flex items-center space-x-4">
                            <input type="hidden" name="hero_bg_path" id="hero_bg_path_input" value="<?php echo get_setting('hero_bg_path'); ?>">
                            <div class="w-24 h-12 bg-white/10 border border-gray-800 rounded-md overflow-hidden flex items-center justify-center cursor-pointer" onclick="openSettingsMediaPicker('hero')">
                                <img src="<?php echo resolve_url(get_setting('hero_bg_path') ?: '/VIVA/v.jpeg'); ?>" id="hero_preview" alt="Hero Background" class="w-full h-full object-cover">
                            </div>
                            <button type="button" onclick="openSettingsMediaPicker('hero')" class="bg-gray-800 hover:bg-gray-700 text-white font-semibold py-2 px-4 rounded-lg transition-all">
                                Change Hero
                            </button>
                        </div>
                    </div>

                    <div class="mt-8 w-full border-t border-gray-800 pt-6">
                        <div class="flex items-center space-x-3 mb-4">
                            <div class="w-8 h-8 bg-gray-800 rounded-lg flex items-center justify-center text-orange-500">
                                <i class="fas fa-info-circle text-sm"></i>
                            </div>
                            <div>
                                <p class="text-sm font-semibold text-white">About Section Image</p>
                                <p class="text-xs text-gray-500">Select machinery photo for About section</p>
                            </div>
                        </div>
                        <div class="flex items-center space-x-4">
                            <input type="hidden" name="about_image_path" id="about_image_path_input" value="<?php echo get_setting('about_image_path'); ?>">
                            <div class="w-24 h-12 bg-white/10 border border-gray-800 rounded-md overflow-hidden flex items-center justify-center cursor-pointer" onclick="openSettingsMediaPicker('about')">
                                <img src="<?php echo resolve_url(get_setting('about_image_path') ?: '/VIVA/v.jpeg'); ?>" id="about_preview" alt="About Image" class="w-full h-full object-cover">
                            </div>
                            <button type="button" onclick="openSettingsMediaPicker('about')" class="bg-gray-800 hover:bg-gray-700 text-white font-semibold py-2 px-4 rounded-lg transition-all">
                                Select Image
                            </button>
                        </div>
                    </div>

                    <div class="mt-8 w-full border-t border-gray-800 pt-6">
                        <div class="flex items-center space-x-3 mb-4">
                            <div class="w-8 h-8 bg-gray-800 rounded-lg flex items-center justify-center text-orange-500">
                                <i class="fas fa-tools text-sm"></i>
                            </div>
                            <div>
                                <p class="text-sm font-semibold text-white">Services Background</p>
                                <p class="text-xs text-gray-500">Select background for services section</p>
                            </div>
                        </div>
                        <div class="flex items-center space-x-4">
                            <input type="hidden" name="services_bg_path" id="services_bg_path_input" value="<?php echo get_setting('services_bg_path'); ?>">
                            <div class="w-24 h-12 bg-white/10 border border-gray-800 rounded-md overflow-hidden flex items-center justify-center cursor-pointer" onclick="openSettingsMediaPicker('services')">
                                <img src="<?php echo resolve_url(get_setting('services_bg_path') ?: '/VIVA/v.jpeg'); ?>" id="services_preview" alt="Services Background" class="w-full h-full object-cover">
                            </div>
                            <button type="button" onclick="openSettingsMediaPicker('services')" class="bg-gray-800 hover:bg-gray-700 text-white font-semibold py-2 px-4 rounded-lg transition-all">
                                Select Background
                            </button>
                        </div>
                    </div>

                    <script>
                    function openSettingsMediaPicker(type) {
                        if (typeof window.openMediaManager !== 'function') {
                            alert('Media Manager is not loaded correctly.');
                            return;
                        }
                        
                        window.openMediaManager({ multiple: false }, function(items) {
                            if (!items || items.length === 0) return;
                            
                            const item = items[0];
                            // item.path is absolute from root (e.g. uploads/...)
                            const finalPath = '/' + item.path.replace(/^\/+/, '');
                            
                            // Dynamic preview using base URL
                            const previewUrl = window.VIVA_BASE_URL + finalPath;

                            if (type === 'logo') {
                                document.getElementById('logo_path_input').value = finalPath;
                                document.getElementById('logo_preview').src = previewUrl;
                            } else if (type === 'favicon') {
                                document.getElementById('favicon_path_input').value = finalPath;
                                document.getElementById('favicon_preview').src = previewUrl;
                            } else if (type === 'hero') {
                                document.getElementById('hero_bg_path_input').value = finalPath;
                                document.getElementById('hero_preview').src = previewUrl;
                            } else if (type === 'about') {
                                document.getElementById('about_image_path_input').value = finalPath;
                                document.getElementById('about_preview').src = previewUrl;
                            } else if (type === 'services') {
                                document.getElementById('services_bg_path_input').value = finalPath;
                                document.getElementById('services_preview').src = previewUrl;
                            }
                        });
                    }
                    </script>
                </div>
            </div>
        </div>

        <!-- CTA / Hero Settings -->
        <div class="lg:col-span-2 card p-6">
            <div class="flex items-center space-x-3 mb-6">
                <div class="w-8 h-8 bg-orange-600/10 rounded-lg flex items-center justify-center text-orange-600">
                    <i class="fas fa-bullhorn text-sm"></i>
                </div>
                <h3 class="text-lg font-bold">Homepage Hero & Calls-to-Action</h3>
            </div>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Hero Headline</label>
                    <input type="text" name="hero_headline" value="<?php echo get_setting('hero_headline'); ?>" 
                        class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all"
                        placeholder="Precision engineering for converting & slitting">
                </div>
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Hero Subheadline</label>
                    <input type="text" name="hero_subheadline" value="<?php echo get_setting('hero_subheadline'); ?>" 
                        class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all"
                        placeholder="Turnkey machines built for uptime and accuracy.">
                </div>
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Primary CTA Text</label>
                    <input type="text" name="cta_primary_text" value="<?php echo get_setting('cta_primary_text'); ?>" 
                        class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all"
                        placeholder="Book a Demo">
                </div>
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Primary CTA URL</label>
                    <input type="text" name="cta_primary_url" value="<?php echo get_setting('cta_primary_url'); ?>" 
                        class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all"
                        placeholder="/contact.php">
                </div>
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Secondary CTA Text</label>
                    <input type="text" name="cta_secondary_text" value="<?php echo get_setting('cta_secondary_text'); ?>" 
                        class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all"
                        placeholder="Download Brochure">
                </div>
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Secondary CTA URL</label>
                    <input type="text" name="cta_secondary_url" value="<?php echo get_setting('cta_secondary_url'); ?>" 
                        class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all"
                        placeholder="/assets/brochure.pdf">
                </div>
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Contact CTA Text (Sticky bar/footer)</label>
                    <input type="text" name="contact_cta_text" value="<?php echo get_setting('contact_cta_text'); ?>" 
                        class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all"
                        placeholder="Talk to an engineer">
                </div>
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Contact CTA URL</label>
                    <input type="text" name="contact_cta_url" value="<?php echo get_setting('contact_cta_url'); ?>" 
                        class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all"
                        placeholder="/contact.php#form">
                </div>
            </div>
            <p class="text-xs text-gray-500 mt-3">These texts/links can power your homepage hero buttons or contact strips.</p>
        </div>

        <!-- Analytics & Pixels -->
        <div class="lg:col-span-2 card p-6">
            <div class="flex items-center space-x-3 mb-6">
                <div class="w-8 h-8 bg-indigo-600/10 rounded-lg flex items-center justify-center text-indigo-400">
                    <i class="fas fa-chart-line text-sm"></i>
                </div>
                <h3 class="text-lg font-bold">Analytics & Pixels</h3>
            </div>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">GA4 Measurement ID</label>
                    <input type="text" name="ga_measurement_id" value="<?php echo get_setting('ga_measurement_id'); ?>" 
                        class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all"
                        placeholder="G-XXXXXXXXXX">
                </div>
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Meta Pixel ID</label>
                    <input type="text" name="meta_pixel_id" value="<?php echo get_setting('meta_pixel_id'); ?>" 
                        class="w-full bg-black border border-gray-800 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-orange-600 transition-all"
                        placeholder="123456789012345">
                </div>
            </div>
            <p class="text-xs text-gray-500 mt-3">Add tracking IDs here; your frontend can read and inject scripts conditionally.</p>
        </div>
    </form>
</div>

<?php 
require_once 'includes/footer.php';
?>
