<?php
/**
 * VIVA Site-Wide Settings
 * Auto-generated by Admin Panel
 */

$site_settings = [
    'site_name' => 'VIVA ENGINEERING PVT LTD',
    'site_title' => 'VIVA Engineering - Leading Industrial Machinery Manufacturer',
    'contact_email' => 'info@vivaengineering.com',
    'enquiry_email' => 'sales@vivaengineering.com',
    'whatsapp_number' => '+91 99244 41090',
    'contact_phone' => '+91 92656 09416',
    'address' => 'GIDC Phase III, Ahmedabad, Gujarat, India',
    'working_hours' => 'Mon - Sat: 9:00 AM - 7:00 PM',
    'facebook_url' => 'https://facebook.com/vivaengineering',
    'twitter_url' => '',
    'linkedin_url' => 'https://linkedin.com/company/vivaengineering',
    'instagram_url' => 'https://instagram.com/vivaengineering',
    'primary_color' => '#ff5722',
    'logo_path' => '/VIVA/assets/images/products/whatsapp-image-2026-01-02-at-14.40.27.jpeg',
    'favicon_path' => '/VIVA/viva_favicon_1774247177.png',
    'meta_description' => 'VIVA Engineering manufactures high-quality Slitting &amp; Rewinding Machines, Coating Machines, and industrial processing equipment.',
    'meta_keywords' => 'slitting machine, rewinding machine',
    'hero_headline' => 'Precision engineering for slitting, rewinding &amp; coating',
    'hero_subheadline' => 'Turnkey machinery designed for uptime, accuracy, and scale.',
    'cta_primary_text' => 'Book a Demo',
    'cta_primary_url' => '/contact.php',
    'cta_secondary_text' => 'Download Brochure',
    'cta_secondary_url' => '/assets/brochure.pdf',
    'contact_cta_text' => 'Talk to an engineer',
    'contact_cta_url' => '/contact.php#form',
    'map_embed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d117562.77447475148!2d72.71561005!3d22.95627065!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x395e8717804917bd%3A0xc486dc50a905a5a1!2sVIVA%20ENGINEERING!5e0!3m2!1sen!2sin!4v1711955000000!5m2!1sen!2sin',
    'brochure_url' => '/assets/brochure.pdf',
    'hero_bg_path' => 'https://www.ssab.com/-/media/images/technical-support/how-to-weld/how-to-weld-menu-2-1920x570px-240815v1.gif?m=20240815105849',
    'about_image_path' => '/VIVA/uploads/media/media-viva-69cb734cac3a8.webp',
    'services_bg_path' => '/VIVA/uploads/media/media-viva-69cb75463beed.webp',
    'ga_measurement_id' => '',
    'meta_pixel_id' => '',
    'maintenance_mode' => '1',
    'footer_logo_path' => '/assets/images/products/whatsapp-image-2026-01-02-at-14.40.27.jpeg',
    'preloader_logo_path' => '/uploads/media/viva_import_1774265611_69c1250b611ac.jpeg',
    'popup_enabled' => '1',
    'popup_delay' => '5',
];

/**
 * Helper to get a setting
 */
if (!function_exists('get_setting')) {
    function get_setting($key, $default = '') {
        global $site_settings;
        return $site_settings[$key] ?? $default;
    }
}
?>