<?php
/**
 * VIVA Site-Wide Settings
 * Auto-generated by Admin Panel
 */

$site_settings = [
    'site_name' => 'VIVA ENGINEERING PVT LTD',
    'site_title' => 'VIVA Engineering - Leading Industrial Machinery Manufacturer',
    'contact_email' => 'info@vivaengineering.com',
    'enquiry_email' => 'sales@vivaengineering.com',
    'whatsapp_number' => '+91 98765 43210',
    'contact_phone' => '+91 98765 43210',
    'address' => 'GIDC Phase III, Ahmedabad, Gujarat, India',
    'working_hours' => 'Mon - Sat: 9:00 AM - 7:00 PM',
    'facebook_url' => 'https://facebook.com/vivaengineering',
    'twitter_url' => '',
    'linkedin_url' => 'https://linkedin.com/company/vivaengineering',
    'instagram_url' => 'https://instagram.com/vivaengineering',
    'primary_color' => '#ff5722',
    'logo_path' => '/VIVA/viva_logo_1774091339.png',
    'favicon_path' => '/VIVA/viva_favicon_1774247177.png',
    'meta_description' => 'VIVA Engineering manufactures high-quality Slitting &amp; Rewinding Machines, Coating Machines, and industrial processing equipment.',
    'meta_keywords' => 'slitting machine, rewinding machine',
    'hero_headline' => 'Precision engineering for slitting, rewinding &amp; coating',
    'hero_subheadline' => 'Turnkey machinery designed for uptime, accuracy, and scale.',
    'cta_primary_text' => 'Book a Demo',
    'cta_primary_url' => '/contact.php',
    'cta_secondary_text' => 'Download Brochure',
    'cta_secondary_url' => '/assets/brochure.pdf',
    'contact_cta_text' => 'Talk to an engineer',
    'contact_cta_url' => '/contact.php#form',
    'map_embed' => '',
    'brochure_url' => '/assets/brochure.pdf',
    'hero_bg_path' => '',
    'ga_measurement_id' => '',
    'meta_pixel_id' => '',
    'maintenance_mode' => '0',
    'currency_code' => 'USD',
];

/**
 * Helper to get a setting
 */
if (!function_exists('get_setting')) {
    function get_setting($key, $default = '') {
        global $site_settings;
        return $site_settings[$key] ?? $default;
    }
}
?>